title__mode:
  left:
    - title
  right:
    - mode:
        class: "small-font"
  use_field_names: false
  section: true
  div_class_for_set: flex-container

author__date:
  left:
    - author
  right:
    - date
  use_field_names: false

event__place:
  left:
    - event
    - place
  use_field_names: false
  separator: ". "

technologies:
  left:
    - technologies

book__pages:
  left:
    - book:
        use_field_names: false
    - page
    - original_language:
        use: 'expr params_language != item[["value"]]'
  use_field_names: true
  separator: ". "

proof:
  left:
    - proof:
        use: "expr params_private"
        params_action: mask_link, use_string:Document
  use_field_names: false
