title__year:
  left:
    - title
  right:
    - year
  use_field_names: false
  section: true
  bold: true
  div_class_for_set: flex-container

libraries__challenges__etc:
  left:
    - libraries
    - challenges:
        params_action: mask_link, use_server_and_last_part
    - products:
        params_action: mask_link, use_server_and_last_part
    - platform
  separator: ""
  indent: true

begin__end:
  left:
    - begin
    - end
  spaces: 4
