level__period:
  left:
    - level
  right:
    - period
  use_field_names: false
  bold: true
  section: true
  div_class_for_set: flex-container

title__emphasis:
  left:
    - title
  right:
    - emphasis

diplomadate__validationdate__scholarship:
  left:
    - diplomadate
    - validationdate
  right:
    - scholarship
  spaces: 4
  separator: ""

institution:
  left:
    - institution
  use_field_names: false

thesis__supervisor:
  left:
    - thesis
  right:
    - supervisor

keywords__original_language:
  left:
    - keywords
    - original_language
  separator: ". "

grade__distinctions:
  left:
    - grade
  right:
    - distinctions

proof:
  left:
    - proof:
        use: "expr params_private"
        params_action: mask_link, use_string:Document
  use_field_names: false
