linkedIn__curriculum__etc:
  left:
    - linkedIn:
        params_action: mask_link, use_last_part
    - curriculum:
        params_action: mask_link, use_last_part
    - cvlattes:
        params_action: mask_link, use_last_part
    - gitlab:
        params_action: mask_link, use_last_part
    - github:
        params_action: mask_link, use_last_part
    - orcid:
        params_action: mask_link, use_last_part
    - stack:
        params_action: mask_link, use_last_part
  separator: <br>
