name:
  left:
    - name
  right:
    - picture:
        image: true
        use_field_names: false
        class: right-frame-15
  whole: true

shortName:
  left:
    - shortName:
        use: "expr !params_private"

passport_passportIssuer:
  left:
    - passport
    - passportIssuer
  separator: " "
  whole: true

id_idIssuePlace_idIssueDate:
  left:
    - id
    - idIssuePlace
    - idIssueDate
  separator: " "
  whole: true

bornId_bornIdIssuePlace_bornIdIssueDate:
  left:
    - bornId
    - bornIdIssuePlace
    - bornIdIssueDate
  separator: " "
  whole: true

secondId_secondIdIssuePlace_secondIdIssueDate:
  left:
    - secondId
    - secondIdIssuePlace
    - secondIdIssueDate
  separator: " "
  whole: true

cpf_cnh_pis:
  left:
    - cpf
    - cnh
    - pis
  separator: " "

birthdate_birthCity:
  left:
    - birthdate
    - birthCity
  separator: " "
  whole: true

public_email:
  left:
    - public_email:
        use: "expr !params_private"

email_skype:
  left:
    - email
    - skype

phone_wa__address:
  left:
    - phone_wa
    - address

phone_wa_2__address_2:
  left:
    - phone_wa_2
    - address_2

signature:
  left:
    - signature:
        image: true
        use: "expr params_private"
