title:
  left:
    - title
  use_field_names: false
  section: true

type__etc:
  left:
    - type:
        use_field_names: false
  right:
    - logo:
        image: true
        class: width-6
        use_field_names: false

repo__etc:
  left:
    - repo:
        params_action: mask_link, use_server_and_last_part
    - webpage:
        params_action: mask_link, use_server_name
    - documentation:
        params_action: mask_link, use_server_name
    - publication:
        params_action: mask_link, use_server_name
