title__mode:
  fields_to_render:
    - title
  fields_right:
    - mode:
        class: "small-font"
  use_field_names: false
  section: true
  separator: ". "

author__date:
  fields_to_render:
    - author
  fields_right:
    - date
  use_field_names: false

event__place:
  fields_to_render:
    - event
    - place
  use_field_names: false
  separator: ". "

technologies:
  fields_to_render:
    - technologies

book__pages:
  fields_to_render:
    - book:
        use_field_names: false
    - page
    - original_language:
        use: 'expr params_language != item[["value"]]'
  use_field_names: true
  separator: ". "
