- personal
- chronology
- summary
- links
- development
- positions
- education
- languages
- publications:
    bib: true
- software
- semester_courses
- mentoring
- short_courses:
    params_profile: academic
- talks
- abstracts
- learning
- army:
    use: false
- person_refs
- donate:
    use: false
