title__type:
  left:
    - title
  right:
    - period
  use_field_names: false
  section: true
  div_class_for_set: flex-container

institution__term:
  left:
    - institution
    - url:
        params_action: mask_link, use_field:online_institution
  right:
    - term:
        class: small-font
  use_field_names: false

summary:
  left:
    - summary
  use_field_names: false

type:
  left:
    - type
    - original_language:
        use_field_names: true
        use: 'expr params_language != item[["value"]]'
  use_field_names: false
  separator: ". "

proof:
  left:
    - proof:
        use: "expr params_private"
        params_action: mask_link, use_string:Document
  use_field_names: false
