title__year:
  fields_to_render:
    - title
  fields_right:
    - year
  use_field_names: false
  section: true
  bold: true
  separator: ""

libraries__challenges__etc:
  fields_to_render:
    - libraries
    - challenges:
        params_action: mask_link, use_server_and_last_part
    - products:
        params_action: mask_link, use_server_and_last_part
    - platform
  separator: ""
  indent: true

begin__end:
  fields_to_render:
    - begin
    - end
  spaces: 4
