level__period:
  fields_to_render:
    - level
  fields_right:
    - period
  use_field_names: false
  bold: true
  section: true

title__emphasis:
  fields_to_render:
    - title
  fields_right:
    - emphasis

diplomadate__validationdate__scholarship:
  fields_to_render:
    - diplomadate
    - validationdate
  fields_right:
    - scholarship
  spaces: 4
  separator: ""

institution:
  fields_to_render:
    - institution
  use_field_names: false

thesis__supervisor:
  fields_to_render:
    - thesis
  fields_right:
    - supervisor

keywords__original_language:
  fields_to_render:
    - keywords
    - original_language
  separator: ". "

grade__distinctions:
  fields_to_render:
    - grade
  fields_right:
    - distinctions
