language:
  left:
    - language
  right:
    - year
  use_field_names: false
  bold: true
  section: true
  div_class_for_set: flex-container

test__results:
  left:
    - test
  right:
    - results
  use_field_names: false

proficiency_level__year:
  left:
    - proficiency_level
  use_field_names: false

proof:
  left:
    - proof:
        use: "expr params_private"
        params_action: mask_link, use_string:Document
  use_field_names: false
