title__term:
  fields_to_render:
    - title
  fields_right:
    - term
  use_field_names: false
  section: true
  bold: true

level__period:
  fields_to_render:
    - level:
        use_field_names: true
  fields_right:
    - period:
        use_field_names: false

institution:
  fields_to_render:
    - institution
  use_field_names: false
