title:
  left:
    - title
  section: true
  use_field_names: false

student__period:
  left:
    - student
  right:
    - period:
        use_field_names: false

institution:
  left:
    - institution
