title__period:
  left:
    - title
  right:
    - period
  use_field_names: false
  bold: true
  section: true
  div_class_for_set: flex-container

activity2__scholarship:
  left:
    - activity
    - activity_developer
  right:
    - scholarship
  div_class_for_set: flex-container

notes:
  left:
    - notes
  use_field_names: false
  indent: true

projects__technologies__etc:
  left:
    - projects
    - technologies
    - libraries:
        params_action: sort
        params_profile: developer
    - institution
    - platform
    - company
    - contact
  separator: ""
  indent: true

begin__end:
  left:
    - begin
    - end
  spaces: 4
