title__year:
  fields_to_render:
    - title
  fields_right:
    - year
  use_field_names: false
  section: true

author__journal__volume__pages:
  fields_to_render:
    - author
    - journal
    - volume
    - pages
  use_field_names: false
  separator: ". "

badges__url:
  fields_to_render:
    - badges
  fields_right:
    - url:
        params_action: mask_link
  use_field_names: false
  separator: ""

repo__webpage:
  fields_to_render:
    - repo:
        params_action: mask_link, use_server_and_last_part
    - webpage:
        params_action: mask_link, use_server_name
