title__year:
  left:
    - title
  right:
    - year
  use_field_names: false
  section: true
  div_class_for_set: flex-container

author__journal__volume__pages:
  left:
    - author
    - journal
    - volume:
        custom_field_name: v
    - url:
        params_action: mask_link, use_field:pages
        custom_field_name: p
  use_field_names: false
  separator: ". "

repo__webpage:
  left:
    - repo:
        params_action: mask_link, use_server_and_last_part
    - webpage:
        params_action: mask_link, use_server_name
    - doi:
        params_action: make_badge
        use_field_names: false
