title__term:
  left:
    - title
  right:
    - period:
  use_field_names: false
  section: true
  div_class_for_set: flex-container

level__period:
  left:
    - level:
        use_field_names: true
  right:
    - term
  use_field_names: false

institution:
  left:
    - institution
    - original_language:
        use: 'expr params_language != item[["value"]]'
        use_field_names: true
  use_field_names: false
  separator: ". "
