title:
  left:
    - title
  right:
    - period
  use_field_names: false
  section: true
  div_class_for_set: flex-container

event:
  left:
    - event
  right:
    - term
  use_field_names: false

original_language:
  left:
    - original_language
  use: 'expr params_language != item[["value"]]'

proof:
  left:
    - proof:
        use: "expr params_private"
        params_action: mask_link, use_string:Document
  use_field_names: false
