title__term:
  fields_to_render:
    - title
  fields_right:
    - term
  use_field_names: false
  section: true
  bold: true

event__period:
  fields_to_render:
    - event
  fields_right:
    - period
  use_field_names: false

original_language:
  fields_to_render:
    - original_language
  use: 'expr params_language != item[["value"]]'
