type__title:
  fields_to_render:
    - type
    - title
  fields_right:
    - logo:
        image: true
        class: width-7
  use_field_names: false
  section: true
  separator: ": "

repo:
  fields_to_render:
    - repo:
        params_action: mask_link, use_server_and_last_part
webpage:
  fields_to_render:
    - webpage:
        params_action: mask_link, use_server_name

documentation__publication:
  fields_to_render:
    - documentation:
        params_action: mask_link, use_server_name
    - publication:
        params_action: mask_link, use_server_name
