last_contract:
  left: last_contract
  html_tag: "p"
  use_field_names: false
  indent: true
  css_class: "indented-first-line"
  first_of_section: true

main_language__secondary_language:
  left:
    - main_language
    - secondary_language
  separator: " "
  use_field_names: false
  indent: true
  css_class: indented-first-line

other_languages:
  left:
    - other_languages
  html_tag: p
  separator: ""
  use_field_names: false
  indent: true
  css_class: indented-first-line

biological__biological_tools:
  left:
    - biological
    - biological_tools
  html_tag: p
  separator: ""
  use_field_names: false
  indent: true
  css_class: indented-first-line

spoken_languages:
  left:
    - spoken_languages
  html_tag: p
  separator: ""
  use_field_names: false
  indent: true
  css_class: indented-first-line
