title:
  left:
    - title
  right:
    - date:
        class: small-font
  use_field_names: false
  section: true
  div_class_for_set: flex-container

event__original_language:
  left:
    - event:
        use_field_names: false
    - original_language:
        use_field_names: true
        use: 'expr params_language != item[["value"]]'
  separator: ". "
  use_field_names: false

technologies:
  left:
    - technologies

place:
  left:
    - place
  use_field_names: false
